apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: user
    database: smart_home
    basicAuth: false
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      database: smart_home
    secureJsonData:
      password: password
    isDefault: true
    editable: true